---
title: "Estimating AE risk under varying follow-up times and competing risks"
author: "Lu Mao, KyungMann Kim"
date: today
format: 
  html:
    css: styles.css
    toc: true
bibliography: references.bib
---

## Existing materials

#### ISCB (2023) Invited Session

*Quantification of safety signals in clinical trials: Estimand, estimation, and how would good look like in ten years?* \[[Abstracts](References/abstracts.pdf){target="_blank"}\]

-   [**Kaspar Rufibach**](https://numbersman77.github.io/kasparrufibach/){target="_blank"}: Principled approach to time-to-event endpoints with competing risks, with a focus on analysis of aes \[[slides](References/Rufibach_slides_2023.pdf){target="_blank"}\]
-   **Anja Loos**: Estimands for safety – one size fits all? \[[paper](References/Unkel%20et%20al%20(2019)%20-%20Pharm%20Statist.pdf){target="_blank"}\]
-   **Laura Antolini**: Adverse events with survival outcomes: from clinical questions to methods for statistical analysis \[[PhD dissertation](References/ELENA_phd.pdf){target="_blank"}\]
-   **Kit Roes**: Regulatory perspective on the analysis of safety in clinical trials and beyond \[slides\]

SAVVY site: [https://numbersman77.github.io/savvy/](https://numbersman77.github.io/savvy/){target="_blank"}

-   A consortium of academic and industry partners aiming to use survival analysis techniques to address varying follow-up times and competing events in AE analysis.

### Literature review

-   @unkel2018:
    -   Advocates for a structured framework to define *what* is being estimated in AE analyses (estimand)
    -   Proposes the Aalen-Johansen (AJ) estimator as the most appropriate tool for estimating cumulative AE probabilities in the presence of censoring and competing risks
-   SAVVY publications [@stegherr2021; @stegherr2021a; @stegherr2021b; @rufibach2024]:
    -   In presence of competing events and censoring, considered
        -   Aalen-Johansen (AJ) estimator for cumulative AE probability
        -   Hazard-based estimators (cause-specific hazard)
        -   One minus Kaplan-Meier estimator (uninterpretable)
        -   Incidence proportion (based by censoring) $$
            \mbox{Incidence Proportion (IP)}= \frac{\mbox{Number of patients with at least one AE}}
            {\mbox{Total number of patients in the study group}}
            $$
    -   Advocates for the AJ estimator as the gold standard for estimating cumulative AE probabilities

## *While-on-treatment* approach

-   **Notation**

    -   $D$: time to competing event (death, treatment discontinuation, etc.)
    -   $N(t)$: counting process for (possibly recurrent) AE (${\rm d}N(t)\equiv 0$ for $t>D$)

-   **AJ Estimand**

    -   $E\{N(t)\}$: cumulative incidence/frequency of AE by time $t$
        -   Estimated by AJ estimator
        -   Does not account for time at risk

-   **Average incidence while on treatment**

    -   $E\{N(t)\}/E\{D\wedge t\}$: average number of AE per unit time on treatment (alive) [@mao2023]
        -   $E\{N(t)\}$ estimated by AJ (aka Ghosh-Lin, Gray) estimator
        -   $E\{D\wedge t\}$ estimated by AUC of Kaplan-Meier estimator
    -   Possible extension: average incidence during year 1, 2, etc., per unit time on treatment

-   **Approach**

    -   *Overall estimand*: $$
        l(\tau) = \frac{E\{N(\tau)\}}{E\{D\wedge \tau\}}: \mbox{ Average incidence in }[0, \tau] 
        $$
    -   *Window-specific estimands* $(0=\tau_0<\tau_1<\cdots<\tau_J = \tau)$ \begin{align}
           l(\tau_{j-1}, \tau_j] &= \frac{\mbox{Average number of AE in $[\tau_{j-1}, \tau_j]$}}{\mbox{Average time on treatment in $[\tau_{j-1}, \tau_j]$}}\\
           & = \frac{E\{N(\tau_j)-N(\tau_{j-1})\}}{E\{D\wedge \tau_j - D\wedge \tau_{j-1}\}}\\
           & = \frac{E\{N(\tau_j)-N(\tau_{j-1})\}}{\int_{\tau_{j-1}}^{\tau_j} S(t) {\rm d}t}
        \end{align}
        -   $S(t) = P(D > t)$
        -   $\int_{\tau_{j-1}}^{\tau_j} S(t) {\rm d}t$ is *window mean life* [@paukner2021] in $[\tau_{j-1}, \tau_j]$
    -   *Estimation* $(X=D\wedge C; C \mbox{ is censoring time})$
        -   Numberator: 
        $$
            E\{N(\tau_j)-N(\tau_{j-1})\} = \int_{\tau_{j-1}}^{\tau_j} E\{{\rm d}N(t)\mid X\geq t \} S(t -) {\rm d}t
            $$ 
            estimated by AJ-type estimator
        -   $\int_{\tau_{j-1}}^{\tau_j} S(t) {\rm d}t$: AUC of KM estimator on $(\tau_{j-1}, \tau_j]$
    -   Property:

    $$
      l(\tau) =  \frac{\sum_{j=1}^J \left\{\int_{\tau_{j-1}}^{\tau_j} S(t) {\rm d}t \times l(\tau_{j-1}, \tau_j] \right\}}
      {\sum_{j=1}^J \left\{\int_{\tau_{j-1}}^{\tau_j} S(t) {\rm d}t \right\}}
        $$

## References
